<a href="https://colab.research.google.com/github/visionblack3/MachineLearning/blob/main/Task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
!pip install opendatasets --quiet

In [35]:
import opendatasets as od
import numpy as np
od.download("https://www.kaggle.com/competitions/house-prices-advanced-regression-techniques/data")

Skipping, found downloaded files in "./house-prices-advanced-regression-techniques" (use force=True to force download)


In [22]:
import pandas as pd
data_df=pd.read_csv("house-prices-advanced-regression-techniques/train.csv")
data_df.isna().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ... 
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [23]:
num_data=data_df.select_dtypes(include='number')
cor_data=num_data.corr()
cor_data

Id  MSSubClass  LotFrontage   LotArea  OverallQual  \
Id             1.000000    0.011156    -0.010601 -0.033226    -0.028365   
MSSubClass     0.011156    1.000000    -0.386347 -0.139781     0.032628   
LotFrontage   -0.010601   -0.386347     1.000000  0.426095     0.251646   
LotArea       -0.033226   -0.139781     0.426095  1.000000     0.105806   
OverallQual   -0.028365    0.032628     0.251646  0.105806     1.000000   
OverallCond    0.012609   -0.059316    -0.059213 -0.005636    -0.091932   
YearBuilt     -0.012713    0.027850     0.123349  0.014228     0.572323   
YearRemodAdd  -0.021998    0.040581     0.088866  0.013788     0.550684   
MasVnrArea    -0.050298    0.022936     0.193458  0.104160     0.411876   
BsmtFinSF1    -0.005024   -0.069836     0.233633  0.214103     0.239666   
BsmtFinSF2    -0.005968   -0.065649     0.049900  0.111170    -0.059119   
BsmtUnfSF     -0.007940   -0.140759     0.132644 -0.002618     0.308159   
TotalBsmtSF   -0.015415   -0.238518     0.392075  0.260833     0.537808   
1stFlrSF       0.010496   -0.251758     0.457181  0.299475     0.476224   
2ndFlrSF       0.005590    0.307886     0.080177  0.050986     0.295493   
LowQualFinSF  -0.044230    0.046474     0.038469  0.004779    -0.030429   
GrLivArea      0.008273    0.074853     0.402797  0.263116     0.593007   
BsmtFullBath   0.002289    0.003491     0.100949  0.158155     0.111098   
BsmtHalfBath  -0.020155   -0.002333    -0.007234  0.048046    -0.040150   
FullBath       0.005587    0.131608     0.198769  0.126031     0.550600   
HalfBath       0.006784    0.177354     0.053532  0.014259     0.273458   
BedroomAbvGr   0.037719   -0.023438     0.263170  0.119690     0.101676   
KitchenAbvGr   0.002951    0.281721    -0.006069 -0.017784    -0.183882   
TotRmsAbvGrd   0.027239    0.040380     0.352096  0.190015     0.427452   
Fireplaces    -0.019772   -0.045569     0.266639  0.271364     0.396765   
GarageYrBlt    0.000072    0.085072     0.070250 -0.024947     0.547766   
GarageCars     0.016570   -0.040110     0.285691  0.154871     0.600671   
GarageArea     0.017634   -0.098672     0.344997  0.180403     0.562022   
WoodDeckSF    -0.029643   -0.012579     0.088521  0.171698     0.238923   
OpenPorchSF   -0.000477   -0.006100     0.151972  0.084774     0.308819   
EnclosedPorch  0.002889   -0.012037     0.010700 -0.018340    -0.113937   
3SsnPorch     -0.046635   -0.043825     0.070029  0.020423     0.030371   
ScreenPorch    0.001330   -0.026030     0.041383  0.043160     0.064886   
PoolArea       0.057044    0.008283     0.206167  0.077672     0.065166   
MiscVal       -0.006242   -0.007683     0.003368  0.038068    -0.031406   
MoSold         0.021172   -0.013585     0.011200  0.001205     0.070815   
YrSold         0.000712   -0.021407     0.007450 -0.014261    -0.027347   
SalePrice     -0.021917   -0.084284     0.351799  0.263843     0.790982   

               OverallCond  YearBuilt  YearRemodAdd  MasVnrArea  BsmtFinSF1  \
Id                0.012609  -0.012713     -0.021998   -0.050298   -0.005024   
MSSubClass       -0.059316   0.027850      0.040581    0.022936   -0.069836   
LotFrontage      -0.059213   0.123349      0.088866    0.193458    0.233633   
LotArea          -0.005636   0.014228      0.013788    0.104160    0.214103   
OverallQual      -0.091932   0.572323      0.550684    0.411876    0.239666   
OverallCond       1.000000  -0.375983      0.073741   -0.128101   -0.046231   
YearBuilt        -0.375983   1.000000      0.592855    0.315707    0.249503   
YearRemodAdd      0.073741   0.592855      1.000000    0.179618    0.128451   
MasVnrArea       -0.128101   0.315707      0.179618    1.000000    0.264736   
BsmtFinSF1       -0.046231   0.249503      0.128451    0.264736    1.000000   
BsmtFinSF2        0.040229  -0.049107     -0.067759   -0.072319   -0.050117   
BsmtUnfSF        -0.136841   0.149040      0.181133    0.114442   -0.495251   
TotalBsmtSF      -0.171098   0.391452      0.291066    0.363936    0

In [24]:
req_col=['TotRmsAbvGrd','GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath','TotalBsmtSF','1stFlrSF', '2ndFlrSF','LowQualFinSF','SalePrice','GarageArea','OverallQual']
data_req=data_df.loc[:,req_col]
data_req.loc[:,'TotalBath']=(data_req['BsmtFullBath'].fillna(0)+data_req['BsmtHalfBath'].fillna(0)+data_req['HalfBath'].fillna(0)+data_req['FullBath'].fillna(0))
data_req.loc[:,'Totalsqft']=(data_req['GrLivArea'].fillna(0)+data_req['TotalBsmtSF'].fillna(0)+data_req['1stFlrSF'].fillna(0)+data_req['2ndFlrSF'].fillna(0)+data_req['LowQualFinSF'].fillna(0))


train_df=data_req[['TotRmsAbvGrd','GarageArea','OverallQual','TotalBath','Totalsqft','SalePrice']]
train_df

TotRmsAbvGrd  GarageArea  OverallQual  TotalBath  Totalsqft  SalePrice
0                8         548            7          4       4276     208500
1                6         460            6          3       3786     181500
2                6         608            7          4       4492     223500
3                7         642            7          2       4190     140000
4                9         836            8          4       5541     250000
...            ...         ...          ...        ...        ...        ...
1455             7         460            6          3       4247     175000
1456             7         500            6          3       5688     210000
1457             9         252            7          2       5832     266500
1458             5         240            5          2       3234     142125
1459             6         276            5          3       3768     147500

[1460 rows x 6 columns]

In [ ]:
from sklearn.model_selection import train_test_split
train_set,test_set=train_test_split(train_df,test_size=0.2,random_state=99)
housing=train_set.drop("SalePrice",axis="columns")
housing_label=train_set['SalePrice']
print(housing)
print(housing_label)

      TotRmsAbvGrd  GarageArea  OverallQual  TotalBath  Totalsqft
542              7         583            7          3       5010
1406             5         396            5          2       2304
338              8         440            7          3       4450
17               6         516            4          2       2592
1313            10         779            9          3       6591
...            ...         ...          ...        ...        ...
1092             7         576            6          2       4569
1192             6         250            5          1       3646
1209             8         500            8          3       4980
1059             7         432            6          2       4836
641              7         650            7          4       4915

[1168 rows x 5 columns]
542     213250
1406    133000
338     202500
17       90000
1313    333168
         ...  
1092    136500
1192    125000
1209    290000
1059    220000
641     226000
Name: SalePrice, L

In [25]:
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
my_pipeline = Pipeline([
    ('imputer',SimpleImputer(strategy="median")),
    ('std_scaler',StandardScaler())
])
x_train = my_pipeline.fit_transform(housing)
y_train=housing_label
print(x_train)
print(y_train)

[[ 0.28538384  0.51271158  0.64398801  0.5980009   0.66683476]
 [-0.93114291 -0.35229342 -0.80111861 -0.46511181 -1.33329361]
 [ 0.89364722 -0.14876283  0.64398801  0.5980009   0.25291314]
 ...
 [ 0.89364722  0.12877888  1.36654133  0.5980009   0.64466038]
 [ 0.28538384 -0.18576839 -0.0785653  -0.46511181  0.5382234 ]
 [ 0.28538384  0.82263316  0.64398801  1.66111362  0.59661591]]
542     213250
1406    133000
338     202500
17       90000
1313    333168
         ...  
1092    136500
1192    125000
1209    290000
1059    220000
641     226000
Name: SalePrice, Length: 1168, dtype: int64


In [26]:
data2_df=pd.read_csv("house-prices-advanced-regression-techniques/train.csv")
req_col=['TotRmsAbvGrd','GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath','TotalBsmtSF','1stFlrSF', '2ndFlrSF','LowQualFinSF','GarageArea','OverallQual']
data_req2=data2_df.loc[:,req_col]
data_req2.loc[:,'TotalBath']=(data_req2['BsmtFullBath'].fillna(0)+data_req2['BsmtHalfBath'].fillna(0)+data_req2['HalfBath'].fillna(0)+data_req2['FullBath'].fillna(0))
data_req2.loc[:,'Totalsqft']=(data_req2['GrLivArea'].fillna(0)+data_req2['TotalBsmtSF'].fillna(0)+data_req2['1stFlrSF'].fillna(0)+data_req2['2ndFlrSF'].fillna(0)+data_req2['LowQualFinSF'].fillna(0))
data_req2

TotRmsAbvGrd  GrLivArea  BsmtFullBath  BsmtHalfBath  FullBath  HalfBath  \
0                8       1710             1             0         2         1   
1                6       1262             0             1         2         0   
2                6       1786             1             0         2         1   
3                7       1717             1             0         1         0   
4                9       2198             1             0         2         1   
...            ...        ...           ...           ...       ...       ...   
1455             7       1647             0             0         2         1   
1456             7       2073             1             0         2         0   
1457             9       2340             0             0         2         0   
1458             5       1078             1             0         1         0   
1459             6       1256             1             0         1         1   

      TotalBsmtSF  1stFlrSF  2ndFlrSF  LowQualFinSF  GarageArea  OverallQual  \
0             856       856       854             0         548            7   
1            1262      1262         0             0         460            6   
2             920       920       866             0         608            7   
3             756       961       756             0         642            7   
4            1145      1145      1053             0         836            8   
...           ...       ...       ...           ...         ...          ...   
1455          953       953       694             0         460            6   
1456         1542      2073         0             0         500            6   
1457         1152      1188      1152             0         252            7   
1458         1078      1078         0             0         240            5   
1459         1256      1256         0             0         276            5   

      TotalBath  Totalsqft  
0             4       4276  
1             3       3786  
2             4       4492  
3             2       4190  
4             4       5541  
...         ...        ...  
1455          3       4247  
1456          3       5688  
1457          2       5832  
1458          2       3234  
1459          3       3768  

[1460 rows x 14 columns]

In [27]:
test_df_unproc = data_req2[['TotRmsAbvGrd','TotalBath','GarageArea','Totalsqft','OverallQual']]
x_test = my_pipeline.transform(test_df_unproc.values)
x_test

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(


array([[ 8.93647221e-01, -2.16556593e+00,  3.91545331e+02,
         4.54327864e+03, -3.03111137e+00],
       [-3.22879532e-01, -2.17019163e+00,  3.27960639e+02,
         4.02235341e+03, -3.03185052e+00],
       [-3.22879532e-01, -2.16556593e+00,  4.34898529e+02,
         4.77291099e+03, -3.03111137e+00],
       ...,
       [ 1.50191060e+00, -2.17481732e+00,  1.77669550e+02,
         6.19748203e+03, -3.03111137e+00],
       [-9.31142909e-01, -2.17481732e+00,  1.68998910e+02,
         3.43551519e+03, -3.03258966e+00],
       [-3.22879532e-01, -2.17019163e+00,  1.95010829e+02,
         4.00321738e+03, -3.03258966e+00]])

In [28]:
print(x_train)
print(y_train)
print(x_test)

[[ 0.28538384  0.51271158  0.64398801  0.5980009   0.66683476]
 [-0.93114291 -0.35229342 -0.80111861 -0.46511181 -1.33329361]
 [ 0.89364722 -0.14876283  0.64398801  0.5980009   0.25291314]
 ...
 [ 0.89364722  0.12877888  1.36654133  0.5980009   0.64466038]
 [ 0.28538384 -0.18576839 -0.0785653  -0.46511181  0.5382234 ]
 [ 0.28538384  0.82263316  0.64398801  1.66111362  0.59661591]]
542     213250
1406    133000
338     202500
17       90000
1313    333168
         ...  
1092    136500
1192    125000
1209    290000
1059    220000
641     226000
Name: SalePrice, Length: 1168, dtype: int64
[[ 8.93647221e-01 -2.16556593e+00  3.91545331e+02  4.54327864e+03
  -3.03111137e+00]
 [-3.22879532e-01 -2.17019163e+00  3.27960639e+02  4.02235341e+03
  -3.03185052e+00]
 [-3.22879532e-01 -2.16556593e+00  4.34898529e+02  4.77291099e+03
  -3.03111137e+00]
 ...
 [ 1.50191060e+00 -2.17481732e+00  1.77669550e+02  6.19748203e+03
  -3.03111137e+00]
 [-9.31142909e-01 -2.17481732e+00  1.68998910e+02  3.43551519e

In [37]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_train)

In [38]:
y_pred[:5]

array([234843.0115575 , 109519.18272057, 214326.97625177,  97760.81931609,
       325603.94056396])

In [39]:
some_data = housing.iloc[:5]
some_labels = housing_label.iloc[:5]
proc_data = my_pipeline.transform(some_data)
model.predict(proc_data)

array([234843.0115575 , 109519.18272057, 214326.97625177,  97760.81931609,
       325603.94056396])

In [40]:
list(some_labels)

[213250, 133000, 202500, 90000, 333168]

In [41]:
def mse(target,predicted):
  return np.mean(np.square(target-predicted))

In [42]:
train_mse = mse(y_train,y_pred)
train_rmse = np.sqrt(train_mse)

print(f"Training MSE: {train_mse:.2f}, Training RMSE: {train_rmse:.2f}")

Training MSE: 1630475137.19, Training RMSE: 40379.14
